version: '3.9'
services:
  postgresdb:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./sql-scripts:/scripts
    networks:
      - darknet
    environment:
      - DS_DB=postgres
      - DB_NAME=testdb
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_URL=localhost
      - DB_PORT=5432
      - DB_DATABASE=testdb

  sql-runner:
    image: postgres
    depends_on:
      - postgresdb
    volumes:
      - ./sql-scripts:/scripts
    command: psql -U postgres  -f /service-1/build/sql/create_tables.sql; psql -U postgres  -f /service-2/build/sql/create_tables.sql

  service_1:
    build:
      context: .
      dockerfile: ./service-1/Dockerfile
    ports:
      - 9090:9090
    depends_on:
      - postgresdb
    networks:
      - darknet

  service_2:
     build:
       context: .
       dockerfile: ./service-2/Dockerfile
     ports:
       - 6969:6969
     depends_on:
       - postgresdb
     networks:
       - darknet

networks:
  darknet:
    driver: bridge

volumes:
  scripts: