version: '3.9'
services:
  postgresdb:
    container_name: postgresdb
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - darknet
    environment:
      - DS_DB=postgres
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_URL=postgresdb
      - DB_PORT=5432
      - DB_DATABASE=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_URI=postgresdb
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=postgres

  service_1:
    container_name: service1
    build:
      context: ./service-1
      dockerfile: Dockerfile
    ports:
      - 9090:9090
    depends_on:
      - postgresdb
    networks:
      - darknet

  service_2:
     container_name: service2
     build:
       context: ./service-2
       dockerfile: Dockerfile
     ports:
       - 6969:6969
     depends_on:
       - postgresdb
     networks:
       - darknet
#     command:  docker exec -it  postgresdb  bash psql -U postgres -d postgres -W -f ./create_tables.sql

networks:
  darknet:
    driver: bridge

volumes:
  postgres-data:
